name: motile-tracker-conda
channels:
  - conda-forge
  - funkelab
  - gurobi
dependencies:
  - python=3.11.*
  - pip
  - gcg
  - papilo
  - scip
  - soplex
  - zimpl
  - ilpy=0.4.0
  - numpy<2.1
  - pip:
    - git+https://github.com/funkelab/motile_tracker@installer
