name: motile-tracker
channels:
  - conda-forge
  - funkelab
  - gurobi
dependencies:
  - python=3.11.*
  - ilpy
  - scip=9.2.*
  - numpy=2.0.*
  - pip
  - pip:
    - git+https://github.com/funkelab/motile_tracker@installer
