[project]
name = "motile-tracker"
channels = [
  "conda-forge",
  "funkelab",
  "gurobi",
]

platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = [ "pixi-build" ]

[dependencies]
python = "3.11.*"
ilpy = "*"
pip = "*"

[tasks.setup]
cmd = "python -m pip install ."

[tasks.create-package]
depends-on = [ "setup" ]
cmd = "pixi exec constructor ."

[tasks.start]
depends-on = [ "setup" ]
cmd = "python -m motile_tracker.launcher"

[package]
name = "motile-tracker"
version = "v3.1.3"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies]
constructor = "*"
