[project]
name = "motile-tracker"
channels = [
  "conda-forge",
  "funkelab",
  "gurobi"
]

platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = [ "pixi-build" ]

[dependencies]
python = "3.11.*"
pip = "*"
scip = "9.*"
numpy = "2.0.*"
constructor = "*"
pyinstaller = "*"

[pypi-dependencies]
ilpy = "*"
motile_tracker = { path = "." }
napari = { version = "*", extras = [ "all" ] }

[tasks]
setup = "pip install ."
create-package = "constructor . --output-dir dist"
start = "python -m motile_tracker.launcher"
create-app = { depends-on = [ "setup" ], cmd = "pyinstaller motile-tracker.spec" }

[feature.test.dependencies]
pytest = "*"

[feature.test.pypi-dependencies]
motile_tracker = { path = ".", editable = false }

[feature.test.tasks]
test = "pytest tests"

[environments]
test = [ "test" ]

[package]
name = "motile-tracker"
version = "v3.1.3"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }
