[project]
name = "motile-tracker"
channels = [
  "conda-forge",
  "funkelab",
  "gurobi"
]

platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = [ "pixi-build" ]

[dependencies]
python = "3.11.*"
pip = "*"
scip = "9.1.*"
pyinstaller = "*"

[pypi-dependencies]
ilpy = "==0.4.1"
motile_tracker = { path = ".", editable = true }

[tasks]
setup = { cmd = "pip install ." }
start = { cmd = "python -m motile_tracker.launcher" }
create-app = { cmd = "pyinstaller motile-tracker.spec", outputs = [ "dist/MotileTracker" ] }
package-app = { cmd = "echo Package app" }

[feature.test.dependencies]
pytest = "*"

[feature.test.pypi-dependencies]
motile_tracker = { path = ".", editable = false }

[feature.test.tasks]
test = "pytest tests"

[target.osx-arm64.tasks.package-app]
cmd = "install-scripts/create-dmg.sh"
outputs = [ "dist/MotileTracker.dmg" ]

[target.win-64.tasks.package-app]
cmd = "iscc install-scripts/wininstaller.iss"

[target.linux-64.tasks.package-app]
cmd = "cp install-scripts/finalize-install.sh dist/MotileTracker && makeself --target /opt/MotileTracker --license LICENSE dist/MotileTracker dist/MotileTrackerInstaller.run \"MotileTracker Installer\" ./finalize-install.sh"

[environments]
test = [ "test" ]

[package]
name = "motile-tracker"
version = "v3.1.3"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }
